[server]
port = 8501
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 5
headless = true
runOnSave = false
allowRunOnSave = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
showErrorDetails = false

[client]
caching = true
displayEnabled = true
toolbarMode = "minimal"

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "WARNING"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[global]
developmentMode = false
showWarningOnDirectExecution = false
suppressDeprecationWarnings = true
showErrorDetails = false
maxCachedMessageAge = 2